// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgV3FQiNF4Lb-otEEtBZKvVxTffQfFQzA',
    appId: '1:203574439395:android:3280a5d59efb9c80eb04d6',
    messagingSenderId: '203574439395',
    projectId: 'coopgo-b58bd',
    databaseURL: 'https://coopgo-b58bd-default-rtdb.firebaseio.com',
    storageBucket: 'coopgo-b58bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaptL_5g5qAyviwECwmds-4HuD0YBnWkg',
    appId: '1:203574439395:ios:98fd2740abd889a4eb04d6',
    messagingSenderId: '203574439395',
    projectId: 'coopgo-b58bd',
    databaseURL: 'https://coopgo-b58bd-default-rtdb.firebaseio.com',
    storageBucket: 'coopgo-b58bd.appspot.com',
    iosClientId: '203574439395-bh9ebkk5jmalrhprhe0b9m0u0g1fd1jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );
}
